services:
  - type: web
    name: to-do-app-server
    env: docker
    plan: free
    buildCommand: docker build -t to-do-app-server .
    startCommand: java -jar /app/app.jar
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
