services:
  - type: web
    name: to-do-app-server
    env: java
    plan: free
    buildCommand: java -version  # Apenas para verificar se o Java está instalado
    startCommand: java -jar bin/*.jar
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    disk:
      name: tmp
      mountPath: /tmp
