server:
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:h2:file:~/.ToDoApp/database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    com.aduilio.tasks: debug
